import Head from 'next/head'
import {signOut } from 'next-auth/react'

export default function Home() {
  return (
    <div className='space-y-10 relative'>
      <Head>
        <title>Feed | LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      </header>
        <button onClick={() => signOut()}>Sign Out</button>
      <main>INdex.js</main>
    </div>
  )
}
